/**
 * The management API: HTTP + WebSocket over a `BunJobs` context, with OpenAPI
 * and AsyncAPI documents for exactly what is routed.
 *
 * Assembled in work units. This barrel is not yet re-exported from the package
 * root: the public block (`createJobsApi`, the `JOBS_API_*` constants, the
 * `JobsApi*` types and the DTOs) joins `lib/index.ts` when the branch is
 * prepared for merge. Everything else here is internal to the API's units.
 */

export {
  type AuthDecision,
  authorizeHandler,
  type AuthorizeHandlerOptions,
  type AuthorizeRequest,
  type AuthorizeTarget,
  canonicalOrigin,
  checkCsrf,
  csrfGuard,
  csrfInfo,
  type CsrfRequestInfo,
  decide,
  denialError,
  isSameOrigin,
  mediaTypeOf,
  normalizeAuthorizeResult,
  originAllowed,
  type OriginAllowList,
  originGuard,
  originListed,
  requestHost,
  staticDecision,
} from "./auth";
export { bodySizeGuard, emptyBodyAsObject, jsonBodyGuard } from "./body";
export {
  type AsyncApiDocument,
  DEFAULT_JOBS_API_LIMITS,
  isActionEnabled,
  isAddableName,
  isMutation,
  JOBS_API_ACTIONS,
  JOBS_API_MUTATIONS,
  JOBS_API_OPT_IN_ACTIONS,
  type JobsApi,
  type JobsApiAction,
  type JobsApiAuthorize,
  type JobsApiAuthorizeContext,
  type JobsApiAuthorizeResult,
  type JobsApiConfig,
  type JobsApiCsrfOptions,
  type JobsApiDocsOptions,
  type JobsApiLimits,
  type JobsApiListQueues,
  type JobsApiMode,
  type JobsApiRouteInfo,
  type JobsApiSerializers,
  type JobsApiSocketData,
  type JobsApiWebSocket,
  type JobsApiWebSocketOptions,
  type OpenApiDocument,
  type OpenApiSecurityScheme,
  resolveConfig,
  type ResolvedJobsApiConfig,
  type ResolvedJobsApiCsrfOptions,
  type ResolvedJobsApiDocsOptions,
  type ResolvedJobsApiLimits,
  type ResolvedJobsApiSerializers,
  type ResolvedJobsApiWebSocketOptions,
} from "./config";
export { buildJobsApi, builtInRoutes, createJobsApi } from "./createJobsApi";
export {
  API_ERROR_STATUS,
  ApiError,
  type ApiErrorCode,
  type ApiErrorHandlerOptions,
  type ApiErrorOptions,
  type ApiOwnErrorCode,
  createApiErrorHandler,
  createNotFoundHandler,
  errorStatusCode,
  isNotSupportedError,
  mapCallSiteError,
  type ProblemCallSite,
  type ProblemResult,
  problemTitle,
  problemType,
  requestActionOf,
  sendProblem,
  tagRequestAction,
  toProblem,
  type ToProblemOptions,
} from "./errors";
export {
  ANALYTICS_METHODS,
  analyticsMetaOf,
  analyticsRoutes,
  DEFAULT_BUSYNESS_INTERVAL_MS,
  rangeDto,
  requestedRange,
  resolveRange,
  servesAnalytics,
} from "./routes/analytics";
export {
  type AnyRouteDef,
  defaultStatus,
  defineRoute,
  isRouteEnabled,
  joinPath,
  registerRoutes,
  type ResponseBody,
  type RouteContext,
  type RouteDef,
  type RouteMethod,
  type RouteMode,
  type RouteResponses,
  type RouteResult,
  type RouteServices,
} from "./routes/define";
export { docsRoutes } from "./routes/docs";
export { jobRoutes } from "./routes/jobs";
export {
  actionMode,
  buildMeta,
  DRIVER_FEATURES,
  driverImplements,
  evaluatePermissions,
  JOBS_API_PROTOCOL_VERSION,
  metaRoutes,
  probeFeatures,
} from "./routes/meta";
export { queueRoutes, summarizeQueue } from "./routes/queues";
export { repeatableRoutes } from "./routes/repeatables";
export { runnerRoutes } from "./routes/runners";
export {
  bulkIds,
  FAN_OUT,
  jobNotFound,
  JobParams,
  mapBounded,
  QueueNameSchema,
  QueueParams,
  queueTarget,
  REMOTE_LATENCY_NOTE,
  RepeatableParams,
  RunnerParams,
  runnerTarget,
  stateConflict,
  toEpoch,
  WorkerConfigParams,
  workerKeyTarget,
  WorkerNameSchema,
  WorkerParams,
  workerTarget,
} from "./routes/support";
export {
  supportsRemoteWorkerControl,
  WORKER_ACK_POLL_MS,
  workerRoutes,
  workerStateOf,
} from "./routes/workers";
export {
  type ArrayOptions,
  type BooleanOptions,
  type DefaultedSchema,
  type EnumOptions,
  type Infer,
  namedSchemaOf,
  type NumberOptions,
  type ObjectOptions,
  type ObjectOut,
  type Optional,
  type PropertySchema,
  s,
  type Schema,
  type StringOptions,
  toJsonSchema,
  type ToJsonSchemaOptions,
} from "./schema/builder";
export {
  coerceArray,
  coerceBoolean,
  coerceForTypes,
  coerceNumber,
} from "./schema/coerce";
export {
  compilePattern,
  isDateTime,
  type JsonPrimitive,
  type JsonSchema,
  type JsonSchemaType,
  validateJson,
  type ValidateJsonOptions,
} from "./schema/validate";
export {
  analyticsRangeQuerySchema,
  AnalyticsRangeSchema,
  JobsSeriesSchema,
  OverviewAnalyticsSchema,
  rangeQueryProperties,
  RunnerAnalyticsSchema,
  runnersAnalyticsQuerySchema,
  RunnersAnalyticsSchema,
  WorkerAnalyticsSchema,
  workersAnalyticsQuerySchema,
  WorkersAnalyticsSchema,
} from "./schemas/analytics";
export {
  ErrorDtoSchema,
  JOB_STATES,
  JobRefSchema,
  JobStateSchema,
  PageInfoSchema,
  pageOf,
  ProblemIssueSchema,
  ProblemSchema,
} from "./schemas/common";
export {
  AddBodySchema,
  AddResultSchema,
  bulkBodySchema,
  bulkRetryBodySchema,
  ChildrenSchema,
  DefinitionListSchema,
  IncludeQuerySchema,
  JobFlowSchema,
  JobIdRefSchema,
  JobIdSchema,
  JobIncludeSchema,
  jobListQuerySchema,
  JobOptionsSchema,
  JobPageSchema,
  JobSchema,
  LogPageSchema,
  logsQuerySchema,
  lookupBodySchema,
  LookupResultSchema,
  NewJobIdSchema,
  RepeatableSchema,
  retryAllBodySchema,
  RetryAllResultSchema,
  RetryBodySchema,
  UpdateBodySchema,
} from "./schemas/jobs";
export {
  DriverCapabilitiesSchema,
  MetaSchema,
  OpenApiDocumentSchema,
  PermissionsQuerySchema,
  PermissionsSchema,
} from "./schemas/meta";
export {
  cleanBodySchema,
  CleanResultSchema,
  CountResultSchema,
  DrainBodySchema,
  JobCountsSchema,
  OverviewSchema,
  PausedSchema,
  QueueDetailSchema,
  QueueLimitsInputSchema,
  QueueListQuerySchema,
  QueueListSchema,
  QueueSummarySchema,
  StoredLimitsSchema,
} from "./schemas/queues";
export {
  historyQuerySchema,
  HistorySchema,
  KillBodySchema,
  KillResultSchema,
  ResumeBodySchema,
  RunnerIdSchema,
  RunnerInfoSchema,
  RunnerListSchema,
  RunnerPausedSchema,
  RunnerScheduleSchema,
  RunnerStatsSchema,
  RunRecordSchema,
  ScheduleBodySchema,
  ScheduleResultSchema,
  TriggerBodySchema,
  TriggerOutcomeSchema,
} from "./schemas/runners";
export {
  queueWorkerListQuerySchema,
  WorkerConfigBodySchema,
  WorkerConfigListSchema,
  WorkerConfigOverrideSchema,
  WorkerConfigPatchSchema,
  WorkerConfigResultSchema,
  WorkerConfigSchema,
  WorkerConfigValuesSchema,
  WorkerControlBodySchema,
  WorkerControlResultSchema,
  WorkerControlSchema,
  workerListQuerySchema,
  WorkerListSchema,
  WorkerSchema,
  WorkerStateSchema,
  WorkerStopPersistenceSchema,
} from "./schemas/workers";
export {
  type ErrorDto,
  type EventDto,
  isWorkerStale,
  JOB_INCLUDES,
  JOB_LIST_INCLUDE,
  JOB_READ_INCLUDE,
  type JobDto,
  type JobDtoInput,
  type JobFlowDto,
  type JobInclude,
  type JobPageDto,
  type JobWorkerDto,
  type MetaDto,
  type PageDto,
  type PageInfoDto,
  type ProblemDto,
  type ProblemIssueDto,
  type QueueSummaryDto,
  type RepeatableDto,
  type RunnerInfoDto,
  type RunRecordDto,
  STALE_REPORTS,
  toErrorDto,
  toEventDto,
  toJobDto,
  toJobWorkerDto,
  toRepeatableDto,
  toRunnerInfoDto,
  toRunRecordDto,
  toWorkerDto,
  type WorkerDto,
  type WorkerInfoLike,
} from "./serialize";
export {
  type LocalOnlyOperation,
  parseSegment,
  QueueSource,
  type ResolvedRunner,
  RunnerSource,
  type SegmentKind,
  type SourceOptions,
} from "./sources";
export {
  generateOpenApi,
  routeErrorCodes,
  toOpenApiPath,
} from "./spec/openapi";
export {
  collectRefs,
  danglingRefs,
  pruneSchemaComponents,
  resolveRef,
  SCHEMA_REF_PREFIX,
} from "./spec/refs";
export {
  type AsyncApiSecurityScheme,
  type MappedAsyncApiScheme,
  type OpenApiSecurity,
  openApiSecurity,
  toAsyncApiSecurityScheme,
} from "./spec/security";
