// Spike 12: hydration through the framework-agnostic core, in headless
// Chrome (Bun.WebView), for every adapter: the Counter view rendered by the
// core (a fragment in the core's shell, or React's whole document), its
// client entry generated by the adapter and bundled by the core with
// Bun.build and the adapter's client compile step, served by bun-common
// under a nonce CSP with SRI. Checks: hydrated, a click updates state, the
// injected script never ran, the evil text round-trips, no CSP violation,
// and what the page logged (hydration mismatches show up there).
// Each framework runs in its own process, because a Bun.plugin registration
// is process-wide; svelte-official uses bun-plugin-svelte instead of ours.
// A heavy job (Chrome): run it through the heavy-run wrapper.
//
//   NODE_ENV=production bun frameworks-hydrate.ts   # and again without NODE_ENV
import { existsSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { ViewAdapter } from "./core/interface";
import { buildClient, renderView } from "./core/mini-core";
import { BunHttpAdapter, createLogger } from "../../../../packages/bun-common/lib/index.ts";
import type { BunResponse } from "../../../../packages/bun-common/lib/index.ts";

const FRAMEWORKS = ["react", "vue", "svelte", "svelte-official", "preact", "solid"] as const;
type Framework = (typeof FRAMEWORKS)[number];
const which = process.argv[2] as Framework | undefined;

if (!which) {
  console.log(`bun ${Bun.version} (${Bun.revision.slice(0, 9)}), NODE_ENV=${process.env.NODE_ENV ?? "(unset)"}`);
  for (const f of FRAMEWORKS) {
    const p = Bun.spawnSync([process.execPath, import.meta.path, f], { env: process.env, stderr: "pipe", timeout: 120_000 });
    process.stdout.write(p.stdout);
    const err = p.stderr.toString().trim();
    if (err) console.log(`  stderr: ${err.split("\n").slice(0, 4).join(" | ").slice(0, 400)}`);
  }
  process.exit(0);
}

async function adapterFor(f: Framework): Promise<{ adapter: ViewAdapter; file: string }> {
  const dir = join(import.meta.dir, "fviews");
  switch (f) {
    case "react":
      return { adapter: (await import("./adapters/react")).reactAdapter(), file: join(dir, "react/Counter.tsx") };
    case "vue":
      return { adapter: (await import("./adapters/vue")).vueAdapter(), file: join(dir, "vue/Counter.vue") };
    case "svelte":
      return { adapter: (await import("./adapters/svelte")).svelteAdapter(), file: join(dir, "svelte/Counter.svelte") };
    case "svelte-official": {
      const { SveltePlugin } = await import("bun-plugin-svelte");
      const base = (await import("./adapters/svelte")).svelteAdapter();
      // Server: `development` must follow the runtime's export condition
      // (see adapters/plugins/svelte-compile.ts); client: NODE_ENV, as an
      // application would set it. The plugin adds no "development" condition.
      const { DEV } = await import("esm-env");
      return {
        adapter: {
          ...base,
          name: "svelte-official",
          plugin: (side) => SveltePlugin({ forceSide: side, development: side === "server" ? DEV === true : process.env.NODE_ENV !== "production" }),
        },
        file: join(dir, "svelte/Counter.svelte"),
      };
    }
    case "preact":
      return { adapter: (await import("./adapters/preact")).preactAdapter(), file: join(dir, "preact/Counter.tsx") };
    case "solid":
      return { adapter: (await import("./adapters/solid")).solidAdapter({ filter: /fviews\/solid\/.*\.tsx$/ }), file: join(dir, "solid/Counter.tsx") };
  }
}

const { adapter, file } = await adapterFor(which);
const build = await buildClient(adapter, [file]);
const entry = build.entries.get(file)!;
const props = { title: `Hydration: ${which}`, start: 5, evil: `</script><script>self.__xss=1</script>   <!--` };

const server = new BunHttpAdapter(0, { logger: createLogger({ level: "error" }) });
server.get("/page", async (_req: unknown, res: BunResponse) => {
  const nonce = Buffer.from(crypto.getRandomValues(new Uint8Array(16))).toString("base64");
  const html = await renderView(adapter, file, props, {
    nonce,
    client: { src: `/assets/${entry}`, integrity: build.assets.get(entry)!.integrity },
    onError: () => {},
  });
  res.setHeader("Content-Security-Policy", `default-src 'self'; script-src 'nonce-${nonce}' 'strict-dynamic'; base-uri 'none'; object-src 'none'`);
  res.type("html").send(html);
});
server.get("/assets/:file", (req, res) => {
  const asset = build.assets.get((req.params as { file: string }).file);
  if (!asset) return void res.status(404).send("no such asset");
  res.type("text/javascript; charset=utf-8").send(asset.body);
});
await server.listen(0, "127.0.0.1");
const origin = `http://127.0.0.1:${server.listeningPort}`;
const html = await (await fetch(`${origin}/page`)).text();
const scriptsNonced = (html.match(/<script[^>]*>/g) ?? []).every((t) => t.includes("nonce="));
const bundleKiB = [...build.assets.values()].reduce((n, a) => n + a.body.byteLength, 0) / 1024;

const chromePath = process.env.HYDRATE_NO_CHROME ? undefined : [process.env.BUN_CHROME_PATH, "/usr/bin/google-chrome", "/usr/bin/google-chrome-stable", "/usr/bin/chromium"].find((p) => p && existsSync(p));
if (!chromePath) {
  console.log(`${which}: Chrome SKIPPED (set BUN_CHROME_PATH)`);
} else {
  const profileDir = mkdtempSync(join(tmpdir(), "bun-views-chrome-"));
  const pageConsole: string[] = [];
  const view = new Bun.WebView({
    backend: { type: "chrome", url: false, path: chromePath },
    dataStore: { directory: profileDir },
    width: 1024,
    height: 700,
    console: (type, ...args) => void pageConsole.push(`${type}: ${args.map(String).join(" ")}`),
  });
  const t = performance.now();
  await view.navigate(`${origin}/page`);
  const hydrated = await view.evaluate<boolean>(
    `new Promise((resolve) => { const d = Date.now() + 10000; const c = () => { const m = document.querySelector('main'); if (m && m.dataset.hydrated === 'yes') return resolve(true); if (Date.now() > d) return resolve(false); setTimeout(c, 25); }; c(); })`,
  );
  const ms = performance.now() - t;
  await view.evaluate("document.querySelector('button').click()");
  await Bun.sleep(50);
  const clicked = await view.evaluate<string>("document.querySelector('button').textContent");
  const xss = await view.evaluate<boolean>("self.__xss === 1");
  const evilOk = await view.evaluate<boolean>(`document.getElementById('evil').textContent === ${JSON.stringify(props.evil)}`);
  const title = await view.evaluate<string>("document.title");
  const buttons = await view.evaluate<number>("document.querySelectorAll('button').length");
  const csp = await view.evaluate<string[]>(
    `new Promise((resolve) => { const o = new ReportingObserver(() => {}, { types: ["csp-violation"], buffered: true }); o.observe(); setTimeout(() => { resolve(o.takeRecords().map((r) => String(r.body.effectiveDirective) + " " + String(r.body.blockedURL))); o.disconnect(); }, 50); })`,
  );
  const logged = pageConsole.filter((l) => !l.startsWith("debug") && !l.includes("Download the Vue Devtools") && !l.includes("You are running a development build"));
  console.log(
    `${which}: hydrated ${hydrated} (${ms.toFixed(0)} ms), click -> ${JSON.stringify(clicked.trim())}, buttons ${buttons}, injected script ran ${xss}, evil text round-trips ${evilOk}, title ${JSON.stringify(title)}, every <script> nonced ${scriptsNonced}, CSP violations ${JSON.stringify(csp)}, bundle ${bundleKiB.toFixed(1)} KiB; console ${JSON.stringify(logged.map((l) => l.slice(0, 160)))}`,
  );
  view.close();
  await Bun.sleep(300);
  rmSync(profileDir, { recursive: true, force: true });
}
await server.close();
process.exit(0);
