import type { HmacSha256 } from "../../lib/remote/mac";
import type {
  AcceptVector,
  FrameVectors,
} from "../../scripts/generate-frame-vectors";
import { Buffer } from "node:buffer";
import { createHmac } from "node:crypto";
import { describe, expect, it } from "bun:test";
import { nodeHmacSha256 } from "../../lib/remote/host/mac";
import { subtleHmacSha256 } from "../../lib/remote/mac";
import { decodeTextFrame } from "../../lib/remote/protocol/frame";
import {
  generateFrameVectors,
  renderFrameVectors,
  VECTOR_SECRET,
  VECTORS_PATH,
} from "../../scripts/generate-frame-vectors";

/**
 * The text frame's test vectors (appendix V of `PROTOCOL.md`, RT §11.5):
 * generated by `scripts/generate-frame-vectors.ts`, committed, and checked
 * here three ways, so neither the file nor the codec can drift:
 *
 * 1. the committed file is exactly what the generator writes now;
 * 2. every MAC is recomputed from the vector's own fields by an HMAC that
 *    shares no code with the codec, and four were computed with `openssl`;
 * 3. every accepted frame decodes, and every rejected one is refused for
 *    its stated reason, through both MACs of the seam.
 */

const committedText = await Bun.file(VECTORS_PATH).text();
const committed = JSON.parse(committedText) as FrameVectors;
const key = new TextEncoder().encode(VECTOR_SECRET);

const MACS: { name: string; fn: HmacSha256 }[] = [
  { name: "crypto.subtle", fn: subtleHmacSha256 },
  { name: "node:crypto", fn: nodeHmacSha256 },
];

/** A vector's MAC, from its fields alone. */
function independentMac(vector: AcceptVector): string {
  const input = [
    "BJ1",
    vector.sid,
    vector.dir,
    String(vector.seq),
    String(vector.ack),
    vector.json,
  ].join("\n");
  return createHmac("sha256", VECTOR_SECRET)
    .update(input, "utf8")
    .digest("hex");
}

describe("the committed vectors file", () => {
  it("is exactly what the generator writes", async () => {
    expect(committedText).toBe(await renderFrameVectors());
  });

  it("a file with one byte changed is not (the control)", async () => {
    const at = committedText.indexOf(committed.accept[2]!.mac) + 7;
    const flipped =
      committedText.slice(0, at) +
      String.fromCharCode(committedText.charCodeAt(at) ^ 1) +
      committedText.slice(at + 1);
    expect(flipped).not.toBe(committedText);
    expect(flipped).not.toBe(await renderFrameVectors());
  });

  it("is deterministic: two runs agree", async () => {
    expect(await generateFrameVectors()).toEqual(await generateFrameVectors());
  });

  it("covers the handshake, both directions, ack, UTF-8, the largest seq and http-stream", () => {
    const names = committed.accept.map((vector) => vector.name);
    for (const word of [
      "hello",
      "welcome",
      "invoke",
      "accepted",
      "bare ack",
      "outside ASCII",
      "largest",
      "http-stream",
    ]) {
      expect(names.some((name) => name.includes(word))).toBe(true);
    }
    expect(new Set(committed.accept.map((vector) => vector.dir))).toEqual(
      new Set(["g", "e"]),
    );
    expect(committed.reject.length).toBeGreaterThanOrEqual(8);
  });
});

describe("every MAC, recomputed without the codec", () => {
  for (const vector of committed.accept) {
    it(vector.name, () => {
      expect(vector.macInput).toBe(
        `BJ1\n${vector.sid}\n${vector.dir}\n${vector.seq}\n${vector.ack}\n${vector.json}`,
      );
      expect(independentMac(vector)).toBe(vector.macHex);
      expect(Buffer.from(vector.macHex, "hex").toString("base64url")).toBe(
        vector.mac,
      );
      expect(vector.frame).toBe(
        `BJ1 ${vector.seq} ${vector.ack} ${vector.mac} ${vector.json}`,
      );
    });
  }

  it("four MACs match what openssl computed for them", () => {
    // `printf '%s' "$macInput" | openssl dgst -sha256 -hmac bun-jobs-test-secret`,
    // run once by hand: a bug shared by both MACs of the seam cannot hide here.
    const openssl: Record<number, string> = {
      0: "0b6e7c8416cc53240ee8bd1e01779f4edf48c9820cb32b0618868d443780ca27",
      3: "bd28a8a893c8723fa8a325ce01f04abdca75721ae3847e32f218eace1d93ff7b",
      5: "1e0279a8b8b0f9baefb5857d563a7049072ebd480a8e331b7dd71f3774e4eb1a",
      7: "ec822dd914b20239eaa97dbaefebfbdbbf34d0ad0db77303bac57be382ee0ef2",
    };
    for (const [index, hex] of Object.entries(openssl)) {
      expect(committed.accept[Number(index)]!.macHex).toBe(hex);
    }
  });

  it("the http-stream vector's SSE event carries the frame unchanged", () => {
    const stream = committed.accept.find((vector) => vector.sse)!;
    expect(stream.sse).toBe(
      `id: ${stream.seq}\nevent: ${JSON.parse(stream.json).op}\ndata: ${stream.frame}\n\n`,
    );
  });
});

describe("the codec against the vectors", () => {
  for (const mac of MACS) {
    describe(mac.name, () => {
      for (const vector of committed.accept) {
        it(`accepts: ${vector.name}`, async () => {
          const result = await decodeTextFrame(vector.frame, {
            keys: [key],
            sid: vector.sid,
            dir: vector.dir,
            mac: mac.fn,
          });
          expect(result.ok).toBe(true);
          expect(result.ok && [result.frame.seq, result.frame.ack]).toEqual([
            vector.seq,
            vector.ack,
          ]);
          expect(result.ok && result.frame.json).toBe(vector.json);
        });
      }

      for (const vector of committed.reject) {
        it(`refuses (${vector.reason}): ${vector.name}`, async () => {
          expect(
            await decodeTextFrame(vector.frame, {
              keys: [key],
              sid: vector.sid,
              dir: vector.dir,
              mac: mac.fn,
            }),
          ).toMatchObject({ ok: false, reason: vector.reason });
        });
      }

      it("one flipped byte in an accepted frame is refused (the control)", async () => {
        const vector = committed.accept[3]!;
        const at = vector.frame.length - 5;
        const flipped =
          vector.frame.slice(0, at) +
          String.fromCharCode(vector.frame.charCodeAt(at) ^ 1) +
          vector.frame.slice(at + 1);
        expect(
          await decodeTextFrame(flipped, {
            keys: [key],
            sid: vector.sid,
            dir: vector.dir,
            mac: mac.fn,
          }),
        ).toMatchObject({ ok: false, reason: "mac" });
      });
    });
  }
});
