#!/usr/bin/env bun
/**
 * Generates the typed verb overloads in `lib/BunRouter.ts`.
 *
 * Each route-registering verb gets one overload per chain length, so a handler
 * registered after a `BunValidate` middleware sees the parsed `query`/`body`,
 * and `params` comes from the path literal unless a validator overrode it.
 *
 * They have to be *generated* rather than written once and reused:
 *
 *   - a single variadic overload cannot work, because each position's type
 *     depends on the ones before it and TypeScript then has no inference site;
 *   - declaring the set once and merging it in via an interface fails too —
 *     merged members are appended *after* the class's own, so the existing wide
 *     `(path: string, ...callbacks: RouterHandler[])` signature wins and the
 *     handler degrades to `any`;
 *   - overloads for one member must be adjacent to its implementation, so they
 *     cannot be collected in a single block elsewhere in the class.
 *
 * That leaves inserting them ahead of each verb's existing overloads, which is
 * what this script does — idempotently, between the markers below.
 *
 *   bun scripts/generate-verb-overloads.ts          # rewrite in place
 *   bun scripts/generate-verb-overloads.ts --check  # fail if out of date
 */
import process from "node:process";

/** How many handlers may precede the final one and still be inferred. */
const MAX_PRECEDING = 8;

/**
 * Members matching the verb anchor that are not route registrations. `use`
 * mounts middleware on a path *prefix*, so a path literal there does not
 * describe the params a handler receives.
 */
const EXCLUDED = new Set(["use"]);

/** Files carrying verb overloads, relative to this script. */
/**
 * Files carrying verb overloads, with how each refers to its mount context.
 *
 * `BunRouter` is mountable, so its overloads read the class's own type
 * parameters. The Nest adapter is always a root — it is handed to Nest, never
 * passed to `use()` — so its mount contributes nothing.
 */
const TARGETS = [
  {
    file: "../lib/BunRouter.ts",
    mountPath: "TMountPath",
    mountShape: "TMountShape",
  },
  {
    file: "../../bun-nest/lib/BunHttpAdapter.ts",
    mountPath: '""',
    mountShape: "EmptyShape",
  },
];

const BEGIN = "  /* --- BEGIN generated typed overloads:";
const END = "  /* --- END generated typed overloads:";

/**
 * Builds the overload block for one verb.
 *
 * Exactly **one** position carries a shape — the validator immediately before
 * the final handler. An earlier design let every position carry one, so that
 * several validators could accumulate; it worked in isolation but collapsed in
 * the real class: as soon as any shape position received a non-validator, the
 * overload was discarded and the call silently fell through to the untyped
 * `(path, ...callbacks)` signature. Since `BunValidate` already takes every
 * target in a single call, one shape position loses nothing in practice and
 * resolves reliably.
 *
 * Preceding positions are plain `RouterHandler`, which has a single call
 * signature and therefore still contextually types an inline arrow.
 */
function overloadsFor(
  verb: string,
  mountPath: string,
  mountShape: string,
): string {
  const lines: string[] = [
    `${BEGIN} ${verb} --- */`,
    `  // Generated by scripts/generate-verb-overloads.ts — do not edit by hand.`,
    // `TShape` is a *method* type parameter here even though nothing supplies
    // it, so the handler type stays deferred. Naming `EmptyShape` directly
    // lets TypeScript partially resolve the type, and it then reports the
    // overload as incompatible with the wide implementation signature.
    `  override ${verb}<TPath extends string, TShape = EmptyShape>(`,
    `    path: TPath,`,
    `    handler: MountedHandler<${mountPath}, ${mountShape}, TPath, TShape>,`,
    `  ): this;`,
  ];

  for (let count = 0; count <= MAX_PRECEDING; count++) {
    const positions = Array.from(
      { length: count },
      (_unused, i) => `    handler${i + 1}: RouterHandler,`,
    );

    lines.push(
      `  override ${verb}<TPath extends string, TShape = EmptyShape>(`,
      `    path: TPath,`,
      ...positions,
      `    validator: ValidatorMiddleware<TShape>,`,
      `    handler: MountedHandler<${mountPath}, ${mountShape}, TPath, TShape>,`,
      `  ): this;`,
    );
  }

  lines.push(`${END} ${verb} --- */`);
  return lines.join("\n");
}

/**
 * Inserts (or refreshes) each verb's block immediately above its first existing
 * overload, which is uniformly `override <verb>(path: string, ...callbacks:
 * RouterHandler[]): this;`.
 */
function generate(
  source: string,
  mountPath: string,
  mountShape: string,
): { output: string; verbs: string[] } {
  // Drop any previously generated blocks so the script is idempotent.
  const cleaned = source.replace(
    /^ {2}\/\* --- BEGIN generated typed overloads:[\s\S]*?--- END generated typed overloads: \w+ --- \*\/\n/gm,
    "",
  );

  const anchor =
    /^ {2}override ([a-z]+)\(path: string, \.\.\.callbacks: RouterHandler\[\]\): this;$/gm;

  const verbs: string[] = [];
  const output = cleaned.replace(anchor, (line, verb: string) => {
    if (EXCLUDED.has(verb)) {
      return line;
    }
    verbs.push(verb);
    return `${overloadsFor(verb, mountPath, mountShape)}\n${line}`;
  });

  return { output, verbs };
}

const check = process.argv.includes("--check");
let failed = false;

for (const target of TARGETS) {
  const path = new URL(target.file, import.meta.url).pathname;
  const source = await Bun.file(path).text();
  const { output, verbs } = generate(
    source,
    target.mountPath,
    target.mountShape,
  );
  const label = target.file.replace("../", "");

  if (check) {
    if (output !== source) {
      console.error(
        `${label} is out of date — run this script without --check`,
      );
      failed = true;
    } else {
      console.log(`${label}: up to date (${verbs.length} verbs)`);
    }
    continue;
  }

  await Bun.write(path, output);
  const perVerb = MAX_PRECEDING + 2;
  console.log(
    `${label}: ${verbs.length * perVerb} overloads across ${verbs.length} verbs`,
  );
}

if (failed) {
  process.exit(1);
}
