// Generated by ../measure.ts: ajv standalone (precompiled validator)
// @ts-expect-error generated JS, no declaration
import validate from "./ajv-standalone-validator.js";
export const check = (d: unknown) => validate(d);
check({ id: 1, email: "a@b.c", name: "Ada", age: 36, active: true, role: "admin", createdAt: "2026-10-10T00:00:00Z",
  tags: ["x"], address: { street: "1 Main", city: "Lagos", zip: "100001" },
  orders: [{ id: "o1", total: 9.5, items: [{ sku: "s1", qty: 2 }] }] });
