// Generated by ../measure.ts: ajv (runtime compile)
import Ajv from "ajv";
const validate = new Ajv().compile({"type":"object","required":["id","email","name","active","role","createdAt","tags","address","orders"],"properties":{"id":{"type":"integer"},"email":{"type":"string"},"name":{"type":"string"},"age":{"type":"integer","minimum":0},"active":{"type":"boolean"},"role":{"enum":["admin","user","guest"]},"createdAt":{"type":"string"},"tags":{"type":"array","items":{"type":"string"}},"address":{"type":"object","required":["street","city","zip"],"properties":{"street":{"type":"string"},"city":{"type":"string"},"zip":{"type":"string"}}},"orders":{"type":"array","items":{"type":"object","required":["id","total","items"],"properties":{"id":{"type":"string"},"total":{"type":"number"},"items":{"type":"array","items":{"type":"object","required":["sku","qty"],"properties":{"sku":{"type":"string"},"qty":{"type":"integer"}}}}}}}}});
export const check = (d: unknown) => validate(d);
check({ id: 1, email: "a@b.c", name: "Ada", age: 36, active: true, role: "admin", createdAt: "2026-10-10T00:00:00Z",
  tags: ["x"], address: { street: "1 Main", city: "Lagos", zip: "100001" },
  orders: [{ id: "o1", total: 9.5, items: [{ sku: "s1", qty: 2 }] }] });
