// Generated by ../measure.ts: ky
import ky from "ky";
const api = ky.create({ baseUrl: "https://api.example.test/", retry: 2, timeout: 5000, hooks: { beforeRequest: [({ request }) => { request.headers.set("x", "1"); }] } });
export async function app() {
  const a = await api.get("todos/1").json<{ id: number }>();
  const b = await api.post("todos", { json: { title: "x" } }).json();
  return [a, b];
}
