// Generated by ../measure.ts: @nanostores/query + nanostores + @nanostores/react
import { nanoquery } from "@nanostores/query";
import { useStore } from "@nanostores/react";
const [createFetcherStore, createMutatorStore] = nanoquery({ fetcher: (...keys) => fetch(keys.join("")).then(r => r.json()) });
const $todo = createFetcherStore<string>(["/api/todo/", "1"]);
const $save = createMutatorStore<string>(async ({ data, invalidate }) => { invalidate("/api/todo/1"); return data; });
export function Todo() {
  const q = useStore($todo);
  const m = useStore($save);
  return <button onClick={() => m.mutate("y")}>{q.data}</button>;
}
