// Generated by ../measure.ts: @nanostores/query + nanostores
import { nanoquery } from "@nanostores/query";
export const [createFetcherStore, createMutatorStore, { invalidateKeys }] = nanoquery({ fetcher: (...keys) => fetch(keys.join("")).then(r => r.json()) });
export const $todo = createFetcherStore<string>(["/api/todo/", "1"]);
export const $save = createMutatorStore<string>(async ({ data, invalidate }) => { invalidate("/api/todo/1"); return data; });
$todo.listen(v => console.log(v.data));
