// Generated by ../measure.ts: openapi-fetch
import createClient from "openapi-fetch";
interface paths { "/todos/{id}": { get: { parameters: { path: { id: number } }; responses: { 200: { content: { "application/json": { id: number } } } } } };
  "/todos": { post: { requestBody: { content: { "application/json": { title: string } } }; responses: { 201: { content: { "application/json": { id: number } } } } } } }
const client = createClient<paths>({ baseUrl: "https://api.example.test" });
client.use({ onRequest: ({ request }) => request });
export async function app() {
  const a = await client.GET("/todos/{id}", { params: { path: { id: 1 } } });
  const b = await client.POST("/todos", { body: { title: "x" } });
  return [a.data, b.data];
}
