// Generated by ../measure.ts: spike core + react binding
import { createQueryClient } from "../../swr-core/core";
import { QueryClientProvider, useMutation, useQuery } from "../../swr-core/react";
const client = createQueryClient();
function Todo() {
  const q = useQuery(["todo", 1], async () => ({ data: "x" }), { staleTime: 1000 });
  const s = useQuery(["user"], async () => ({ data: "u" }), { suspense: true });
  const m = useMutation(async (v: string) => v, v => ({ optimistic: c => { const r = c.snapshot(["todo", 1]); c.setQueryData(["todo", 1], v); return r; }, invalidateTags: ["todos"] }));
  return <button onClick={() => m.mutate("y")}>{q.data}{s.data}</button>;
}
export const App = () => <QueryClientProvider client={client}><Todo /></QueryClientProvider>;
