// Generated by ../measure.ts: spike core (swr-core/core.ts)
import { createQueryClient, infiniteQuery } from "../../swr-core/core";
export function app() {
  const c = createQueryClient({ defaults: { staleTime: 1000, retry: 3 } });
  const store = c.watch(["todo", 1], async ({ etag }) => (etag ? { notModified: true } : { data: 1, etag: "v1" }), { refetchInterval: 5000, tags: ["todos"] });
  store.subscribe(() => console.log(store.getSnapshot()));
  c.mutate(async () => 2, { optimistic: x => { const r = x.snapshot(["todo", 1]); x.setQueryData(["todo", 1], 2); return r; }, invalidateTags: ["todos"] });
  c.invalidate({ key: ["todo"] });
  c.hydrate(JSON.parse(JSON.stringify(c.dehydrate())));
  infiniteQuery(c, ["feed"], async ({ pageParam }) => pageParam, { initialPageParam: 0, getNextPageParam: p => p + 1 }).fetchNextPage();
  return c;
}
