// Generated by ../measure.ts: swr
import useSWR, { SWRConfig, preload } from "swr";
import useSWRMutation from "swr/mutation";
import useSWRInfinite from "swr/infinite";
const fetcher = (u: string) => fetch(u).then(r => r.json());
preload("/api/user", fetcher);
function Todo() {
  const q = useSWR("/api/todo/1", fetcher);
  const f = useSWRInfinite((i: number) => "/api/feed?page=" + i, fetcher);
  const m = useSWRMutation("/api/todo/1", (u: string, { arg }: { arg: string }) => fetch(u, { method: "POST", body: arg }));
  return <button onClick={() => m.trigger("y")}>{q.data}{f.size}</button>;
}
export const App = () => <SWRConfig value={{ fetcher, dedupingInterval: 2000 }}><Todo /></SWRConfig>;
