// Generated by ../measure.ts: @tanstack/vue-query
import { QueryClient, VueQueryPlugin, useQuery, useMutation } from "@tanstack/vue-query";
export const plugin = [VueQueryPlugin, { queryClient: new QueryClient() }] as const;
export function setup() {
  const q = useQuery({ queryKey: ["todo", 1], queryFn: async () => "x" });
  const m = useMutation({ mutationFn: async (v: string) => v });
  return { q, m };
}
