// Generated by ../measure.ts: @tanstack/query-core
import { QueryClient, QueryObserver, MutationObserver, InfiniteQueryObserver, dehydrate, hydrate, focusManager, onlineManager } from "@tanstack/query-core";
export function app() {
  const qc = new QueryClient({ defaultOptions: { queries: { staleTime: 1000 } } });
  qc.mount();
  new QueryObserver(qc, { queryKey: ["todo", 1], queryFn: async () => 1 }).subscribe(r => console.log(r.data));
  new InfiniteQueryObserver(qc, { queryKey: ["feed"], queryFn: async ({ pageParam }) => pageParam, initialPageParam: 0, getNextPageParam: (l: number) => l + 1 }).subscribe(() => {});
  new MutationObserver(qc, { mutationFn: async (v: number) => v, onSuccess: () => qc.invalidateQueries({ queryKey: ["todo"] }) }).mutate(2);
  hydrate(qc, dehydrate(qc));
  focusManager.setFocused(true);
  onlineManager.setOnline(true);
  return qc;
}
