// Generated by ../measure.ts: @tanstack/preact-query
import { QueryClient, QueryClientProvider, useQuery, useMutation } from "@tanstack/preact-query";
export { QueryClientProvider };
export const client = new QueryClient();
export function useTodo() {
  const q = useQuery({ queryKey: ["todo", 1], queryFn: async () => "x" });
  const m = useMutation({ mutationFn: async (v: string) => v });
  return { q, m };
}
