// Generated by ../measure.ts: @tanstack/solid-query
import { QueryClient, QueryClientProvider, useQuery, useMutation } from "@tanstack/solid-query";
export { QueryClientProvider };
export const client = new QueryClient();
export function setup() {
  const q = useQuery(() => ({ queryKey: ["todo", 1], queryFn: async () => "x" }));
  const m = useMutation(() => ({ mutationFn: async (v: string) => v }));
  return { q, m };
}
