// Generated by ../measure.ts: @tanstack/svelte-query
import { QueryClient, QueryClientProvider, createQuery, createMutation } from "@tanstack/svelte-query";
export { QueryClientProvider };
export const client = new QueryClient();
export function setup() {
  const q = createQuery(() => ({ queryKey: ["todo", 1], queryFn: async () => "x" }));
  const m = createMutation(() => ({ mutationFn: async (v: string) => v }));
  return { q, m };
}
