// Generated by ../measure.ts: @tanstack/react-query
import { QueryClient, QueryClientProvider, useQuery, useMutation, useSuspenseQuery, useInfiniteQuery, HydrationBoundary } from "@tanstack/react-query";
const qc = new QueryClient();
function Todo() {
  const q = useQuery({ queryKey: ["todo", 1], queryFn: async () => "x" });
  const s = useSuspenseQuery({ queryKey: ["user"], queryFn: async () => "u" });
  const f = useInfiniteQuery({ queryKey: ["feed"], queryFn: async ({ pageParam }) => pageParam, initialPageParam: 0, getNextPageParam: (l: number) => l + 1 });
  const m = useMutation({ mutationFn: async (v: string) => v, onSuccess: () => qc.invalidateQueries({ queryKey: ["todo"] }) });
  return <button onClick={() => m.mutate("y")}>{q.data}{s.data}{f.data?.pages.length}</button>;
}
export const App = (p: { state: import("@tanstack/react-query").DehydratedState }) => <QueryClientProvider client={qc}><HydrationBoundary state={p.state}><Todo /></HydrationBoundary></QueryClientProvider>;
