// Generated by ../measure.ts: valibot
import * as v from "valibot";
const int = () => v.pipe(v.number(), v.integer());
const User = v.object({
  id: int(), email: v.string(), name: v.string(), age: v.optional(v.pipe(v.number(), v.integer(), v.minValue(0))), active: v.boolean(),
  role: v.picklist(["admin", "user", "guest"]), createdAt: v.string(), tags: v.array(v.string()),
  address: v.object({ street: v.string(), city: v.string(), zip: v.string() }),
  orders: v.array(v.object({ id: v.string(), total: v.number(), items: v.array(v.object({ sku: v.string(), qty: int() })) })),
});
export const parse = (d: unknown) => v.parse(User, d);
parse({ id: 1, email: "a@b.c", name: "Ada", age: 36, active: true, role: "admin", createdAt: "2026-10-10T00:00:00Z",
  tags: ["x"], address: { street: "1 Main", city: "Lagos", zip: "100001" },
  orders: [{ id: "o1", total: 9.5, items: [{ sku: "s1", qty: 2 }] }] });
