// Generated by ../measure.ts: zod (classic)
import { z } from "zod";
const User = z.object({
  id: z.number().int(), email: z.string(), name: z.string(), age: z.number().int().min(0).optional(), active: z.boolean(),
  role: z.enum(["admin", "user", "guest"]), createdAt: z.string(), tags: z.array(z.string()),
  address: z.object({ street: z.string(), city: z.string(), zip: z.string() }),
  orders: z.array(z.object({ id: z.string(), total: z.number(), items: z.array(z.object({ sku: z.string(), qty: z.number().int() })) })),
});
export const parse = (d: unknown) => User.parse(d);
parse({ id: 1, email: "a@b.c", name: "Ada", age: 36, active: true, role: "admin", createdAt: "2026-10-10T00:00:00Z",
  tags: ["x"], address: { street: "1 Main", city: "Lagos", zip: "100001" },
  orders: [{ id: "o1", total: 9.5, items: [{ sku: "s1", qty: 2 }] }] });
